/* POPULATES ROOMS BY INCREMENTING THROUGH MAP ARRAY ONCE IMMEDIATELY AFTER
MAP IS GENERATED, CHECKS IF ROOM.EXISTS, AND ADDS A RANDOM MONSTER (D6), AND
TREASURE (D3, LOOT ON 3). */

for(i=0, i<dungeon.length, i++){
  
}
