/* 2D ARRAY OF ROOMS, STARTED FROM THE MIDDLE LEFT, RANDOMLY GENERATED ONCE AT
BEGINNING OF GAME, THREE SIZES (NUMBER OF ROOMS FROM 5-7-9), THAT CONNECT
TO EACHOTHER ONLY IN CARDINAL DIRECTIONS, NO REPEAT GENERATION OR OFF-MAP */ 
